[package]
name = "accessors-rs"
description = "Derive macro generating an impl for accessing the fields of a struct."
license = "MIT"
readme = "README.md"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"